package headers

const (
	Accept         = "Accept"
	AcceptCharset  = "Accept-Charset"
	AcceptFeatures = "Accept-Features"
	AcceptEncoding = "Accept-Encoding"
	AcceptLanguage = "Accept-Language"
	AcceptRanges   = "Accept-Ranges"

	AccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	AccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	AccessControlAllowMethods     = "Access-Control-Allow-Methods"
	AccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	AccessControlMaxAge           = "Access-Control-Max-Age"
	AccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	AccessControlRequestMethod    = "Access-Control-Request-Method"
	AccessControlRequestHeaders   = "Access-Control-Request-Headers"

	ContentEncoding       = "Content-Encoding"
	ContentLanguage       = "Content-Language"
	ContentLength         = "Content-Length"
	ContentLocation       = "Content-Location"
	ContentRange          = "Content-Range"
	ContentSecurityPolicy = "Content-Security-Policy"
	ContentType           = "Content-Type"

	IfMatch           = "If-Match"
	IfModifiedSince   = "If-Modified-Since"
	IfNoneMatch       = "If-None-Match"
	IfRange           = "If-Range"
	IfUnmodifiedSince = "If-Unmodified-Since"

	LastEventID  = "Last-Event-ID"
	LastModified = "Last-Modified"

	ProxyAuthenticate  = "Proxy-Authenticate"
	ProxyAuthorization = "Proxy-Authorization"

	SecWebsocketExtensions = "Sec-Websocket-Extensions"
	SecWebsocketKey        = "Sec-Websocket-Key"
	SecWebsocketOrigin     = "Sec-Websocket-Origin"
	SecWebsocketProtocol   = "Sec-Websocket-Protocol"
	SecWebsocketVersion    = "Sec-Websocket-Version"

	Age                     = "Age"
	Allow                   = "Allow"
	Alternates              = "Alternates"
	Authorization           = "Authorization"
	CacheControl            = "Cache-Control"
	Connection              = "Connection"
	Cookie                  = "Cookie"
	Date                    = "Date"
	ETag                    = "ETag"
	Expect                  = "Expect"
	Expires                 = "Expires"
	From                    = "From"
	Host                    = "Host"
	Link                    = "Link"
	Location                = "Location"
	MaxForwards             = "Max-Forwards"
	Negotiate               = "Negotiate"
	Origin                  = "Origin"
	Pragma                  = "Pragma"
	Range                   = "Range"
	Referer                 = "Referer"
	RetryAfter              = "Retry-After"
	Server                  = "Server"
	SetCookie               = "Set-Cookie"
	SetCookie2              = "Set-Cookie2"
	StrictTransportSecurity = "Strict-Transport-Security"
	TCN                     = "TCN"
	TE                      = "TE"
	Trailer                 = "Trailer"
	TransferEncoding        = "Transfer-Encoding"
	Upgrade                 = "Upgrade"
	UserAgent               = "User-Agent"
	VariantVary             = "Variant-Vary"
	Vary                    = "Vary"
	Via                     = "Via"
	Warning                 = "Warning"
	WWWAuthenticate         = "WWW-Authenticate"
	XContentDuration        = "X-Content-Duration"
	XContentSecurityPolicy  = "X-Content-Security-Policy"
	XDNSPrefetchControl     = "X-DNSPrefetch-Control"
	XFrameOptions           = "X-Frame-Options"
)
