package headers

const (
	Accept         string = "Accept"
	AcceptCharset  string = "Accept-Charset"
	AcceptFeatures string = "Accept-Features"
	AcceptEncoding string = "Accept-Encoding"
	AcceptLanguage string = "Accept-Language"
	AcceptRanges   string = "Accept-Ranges"

	AccessControlAllowCredentials string = "Access-Control-Allow-Credentials"
	AccessControlAllowOrigin      string = "Access-Control-Allow-Origin"
	AccessControlAllowMethods     string = "Access-Control-Allow-Methods"
	AccessControlAllowHeaders     string = "Access-Control-Allow-Headers"
	AccessControlMaxAge           string = "Access-Control-Max-Age"
	AccessControlExposeHeaders    string = "Access-Control-Expose-Headers"
	AccessControlRequestMethod    string = "Access-Control-Request-Method"
	AccessControlRequestHeaders   string = "Access-Control-Request-Headers"

	ContentEncoding       string = "Content-Encoding"
	ContentLanguage       string = "Content-Language"
	ContentLength         string = "Content-Length"
	ContentLocation       string = "Content-Location"
	ContentRange          string = "Content-Range"
	ContentSecurityPolicy string = "Content-Security-Policy"
	ContentType           string = "Content-Type"

	CrossOriginResourcePolicy string = "Cross-Origin-Resource-Policy"
	CrossOriginOpenerPolicy   string = "Cross-Origin-Opener-Policy"
	CrossOriginEmbedderPolicy string = "Cross-Origin-Embedder-Policy"

	IfMatch           string = "If-Match"
	IfModifiedSince   string = "If-Modified-Since"
	IfNoneMatch       string = "If-None-Match"
	IfRange           string = "If-Range"
	IfUnmodifiedSince string = "If-Unmodified-Since"

	LastEventID  string = "Last-Event-ID"
	LastModified string = "Last-Modified"

	ProxyAuthenticate  string = "Proxy-Authenticate"
	ProxyAuthorization string = "Proxy-Authorization"

	SecWebsocketExtensions string = "Sec-Websocket-Extensions"
	SecWebsocketKey        string = "Sec-Websocket-Key"
	SecWebsocketOrigin     string = "Sec-Websocket-Origin"
	SecWebsocketProtocol   string = "Sec-Websocket-Protocol"
	SecWebsocketVersion    string = "Sec-Websocket-Version"

	XContentDuration    string = "X-Content-Duration"
	XContentTypeOptions string = "X-Content-Type-Options"
	XDNSPrefetchControl string = "X-DNSPrefetch-Control"
	XFrameOptions       string = "X-Frame-Options"

	ReferrerPolicy    string = "Referrer-Policy"
	PermissionsPolicy string = "Permissions-Policy"

	Age                     string = "Age"
	Allow                   string = "Allow"
	Alternates              string = "Alternates"
	Authorization           string = "Authorization"
	CacheControl            string = "Cache-Control"
	ClearSiteData           string = "Clear-Site-Data"
	Connection              string = "Connection"
	Cookie                  string = "Cookie"
	Date                    string = "Date"
	ETag                    string = "ETag"
	Expect                  string = "Expect"
	Expires                 string = "Expires"
	From                    string = "From"
	Host                    string = "Host"
	Link                    string = "Link"
	Location                string = "Location"
	MaxForwards             string = "Max-Forwards"
	Negotiate               string = "Negotiate"
	Origin                  string = "Origin"
	Pragma                  string = "Pragma"
	Range                   string = "Range"
	Referer                 string = "Referer"
	RetryAfter              string = "Retry-After"
	Server                  string = "Server"
	SetCookie               string = "Set-Cookie"
	SetCookie2              string = "Set-Cookie2"
	StrictTransportSecurity string = "Strict-Transport-Security"
	TCN                     string = "TCN"
	TE                      string = "TE"
	Trailer                 string = "Trailer"
	TransferEncoding        string = "Transfer-Encoding"
	Upgrade                 string = "Upgrade"
	UserAgent               string = "User-Agent"
	VariantVary             string = "Variant-Vary"
	Vary                    string = "Vary"
	Via                     string = "Via"
	Warning                 string = "Warning"
	WWWAuthenticate         string = "WWW-Authenticate"
)
